---
- name: Install required packages and dependencies
  hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: Install aptitude
      ansible.builtin.apt:
        name: aptitude
        state: present
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - openssl
          - curl
          - gnupg
          - gnupg-agent
          - software-properties-common
          - python3
          - python3-pip
          - python3-apt
          - lsb-release
          - iptables
          - ipset
          - util-linux
          - zfsutils-linux
          - rsync
          - xz-utils
        state: present
      retries: 5
