---
# This file is preconfigured to work with the provided Vagrant virtual machines.
# In order to point to your servers, just modify hosts in 'control_plane' and 'workers' section.
# Currently, only one node in the control plane is supported.
all:
  vars:
    ansible_python_interpreter: /usr/bin/python3
  children:
    control_plane:
      hosts:
        control1:
          ansible_host: 192.168.33.11
          ansible_port: 22
          ansible_user: root
          # Always use ansible_ssh_private_key_file instead of ansible_password! This is just for running tests :
          ansible_password: vagrant
          # ansible_ssh_private_key_file: /path/to/private_key

    workers:
      hosts:
        worker1:
          ansible_host: 192.168.33.12
          ansible_port: 22
          ansible_user: root
          # Always use ansible_ssh_private_key_file instead of ansible_password! This is just for running tests :
          ansible_password: vagrant
          # ansible_ssh_private_key_file: /path/to/private_key

        worker2:
          ansible_host: 192.168.33.13
          ansible_port: 22
          ansible_user: root
          # Always use ansible_ssh_private_key_file instead of ansible_password! This is just for running tests :
          ansible_password: vagrant
          # ansible_ssh_private_key_file: /path/to/private_key

        worker3:
          ansible_host: 192.168.33.14
          ansible_port: 22
          ansible_user: root
          # Always use ansible_ssh_private_key_file instead of ansible_password! This is just for running tests :
          ansible_password: vagrant
          # ansible_ssh_private_key_file: /path/to/private_key
